version: '2'

services:
  
  master:
    image: redis:3.2-alpine
    ports:
      - "36379:6379"

  slave:
    image: redis:3.2-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master
  
  sentinel:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - SENTINEL_QUORUM 1
    links:
      - master:redis-master
      - slave
    ports:
      - "26379:26379"
  
  # proxy:
  #   image: dockercloud/haproxy
  #   depends_on:
  #     - master
  #     - slave
  #     - sentinel
  #   environment:
  #     - BALANCE=leastconn
  #   ports:
  #     - '36379:6379'
  #     - '26379:26379'
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock