version: '3'

services:

  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./storage/rabbitmq1:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cluster-network

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./storage/rabbitmq2:/var/lib/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - cluster-network

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    networks:
      - cluster-network
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq1
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./storage/rabbitmq3:/var/lib/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    ports:
      - "5674:5672"
      - "15674:15672"
    networks:
      - cluster-network
  
networks:
  cluster-network:
    driver: bridge