version: '3.0'

services:
  nginx:
    restart: on-failure
    image: nginx
    ports:
      - 8080:80
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./log:/var/log/nginx
      - ./www:/var/www
    # https://github.com/docker-library/docs/issues/496
    command: /bin/bash -c "envsubst  \"`env | awk -F = '{printf \" $$%s\", $$1}'`\"  < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"