version: "3"

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment: 
      - discovery.type=single-node
    networks: 
      - elk

  logstash:
    build: ./logstash
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes: 
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    networks: 
      - elk

  # redis:
  #   image: redis
  #   container_name: redis
  #   depends_on:
  #     - logstash
  #   ports:
  #     - 6379:6379
  #   logging:
  #     driver: gelf
  #     options:
  #       gelf-address: "udp://localhost:12201"
  #       tag: "redis"

networks: 
  elk:
    driver: bridge