version: "3.3"
services:
  # Redis configuration file example
  # https://raw.githubusercontent.com/antirez/redis/4.0/redis.conf
  master:
    image: redis:4.0.8-alpine
    ports:
      - 16379:6379
    volumes:
      - "./data/master/data:/data"
      - "./data/master/logs:/var/log"
    command: [
      '--logfile "/var/log/redis.log"',
      '--requirepass "${REDIS_PWD}"',
      '--masterauth "${REDIS_PWD}"',
      '--maxmemory 512mb',
      '--maxmemory-policy volatile-ttl',
      '--save ""',
    ]

  node-1: &node
    image: redis:4.0.8-alpine
    depends_on:
      - master
    ports:
      - 6380:6380
    volumes:
      - "./data/node-1/data:/data"
      - "./data/node-1/logs:/var/log"
    command: [
      '--logfile "/var/log/redis.log"',
      '--port 6380',
      '--requirepass "${REDIS_PWD}"',
      '--slaveof master 6379',
      '--masterauth "${REDIS_PWD}"',
      '--save ""',
    ]
    links:
      - master:${SENTINEL_MASTER_NAME}

  node-2: 
    <<: *node
    ports:
      - 6381:6381
    volumes:
      - "./data/node-2/data:/data"
      - "./data/node-2/logs:/var/log"
    command: [
      '--logfile "/var/log/redis.log"',
      '--port 6381',
      '--requirepass "${REDIS_PWD}"',
      '--slaveof master 6379',
      '--masterauth "${REDIS_PWD}"',
      '--save ""',
    ]

  sentinel-1: &sentinel
    build:
      context: ./sentinel
      dockerfile: Dockerfile
    image: redis-sentinel:dev
    environment:
      - SENTINEL_REDIS_PWD=${REDIS_PWD}
      - SENTINEL_REDIS_IP=${SENTINEL_MASTER_NAME}
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=3000
    volumes:
      - "./data/sentinel-1/data:/tmp"
      - "./data/sentinel-1/logs:/var/log"
    command: [
      '${SENTINEL_CONF_PATH}',
      '--sentinel'
    ]
    depends_on:
      - master
      - node-1
      - node-2
    links:
      - master:${SENTINEL_MASTER_NAME}
      - node-1
      - node-2

  sentinel-2:
    <<: *sentinel
    volumes:
      - "./data/sentinel-2/data:/tmp"
      - "./data/sentinel-2/logs:/var/log"

  sentinel-3:
    <<: *sentinel
    volumes:
      - "./data/sentinel-3/data:/tmp"
      - "./data/sentinel-3/logs:/var/log"

  nginx:
    image: nginx:1.13.9-alpine
    ports:
      - 26379:26379
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    depends_on:
      - sentinel-1
      - sentinel-2
      - sentinel-3

