# instructions

version: '3'

services:
  mysql:
    restart: always
    image: 'mysql:5.7'
    container_name: my_mysql
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    restart: always
    image: redis:3.2-alpine
    container_name: my_redis
    ports:
      - "36379:6379"
    volumes:
      - redis-data:/data

  rabbit:
    restart: always
    hostname: rabbit
    image: rabbitmq:latest
    container_name: my_rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    ports:
      - "35672:15672"
      - "3672:5672"
  
  # logging:
  #   driver: "gelf"
  #   options:
  #     gelf-address: "udp://127.0.0.1:12201"  # 127.0.0.1
  #     labels: "dbs"

volumes:
  rabbit-data:
  mysql-data:
  redis-data:

networks:
  default:
    # Use a custom driver
    driver: custom-driver-1
    
# networks:    
#   default:
#     external:
#       name: existing-network