version: '3.4'
services:
  zoo1:
    image: zookeeper
    restart: always
    container_name: zoo1
    ports:
      - "3181:2181"
    expose:
      - "2888"
      - "3888" 
    volumes:
      - ./data/zoo1:/opt/data
      - ./logs/zoo1:/opt/log
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zookeeper
    restart: always
    container_name: zoo2
    ports:
      - "3182:2181"
    expose:
      - "2888"
      - "3888"
    volumes:
      - ./data/zoo2:/opt/data
      - ./logs/zoo2:/opt/log
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zookeeper
    restart: always
    container_name: zoo3
    ports:
      - "3183:2181"
    expose:
      - "2888"
      - "3888"
    volumes:
      - ./data/zoo3:/opt/data
      - ./logs/zoo3:/opt/log
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888

networks:
  default:
    driver: bridge